apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-api
  template:
    metadata:
      labels:
        app: qr-api
    spec:
      containers:
      - name: qr-api
        image: wabsense/devops-qr-code-backend:latest
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: qr-api-service
spec:
  type: ClusterIP
  selector:
    app: qr-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000