name: Build and Deploy
on: 
  workflow_dispatch:
  push:
    paths:
      - 'api/Dockerfile'              # Backend Dockerfile
      - 'front-end-nextjs/Dockerfile' # Frontend Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: wabsense/devops-qr-code-backend:latest
      
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front-end-nextjs
          push: true
          tags: wabsense/devops-qr-code-frontend:latest